# -*- coding: utf-8 -*-
"""K3_iris-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/132C_LMrC8_8-crAXHtNlD4VpAWyfMffZ

Benötigte Module importieren und Datei laden. Die ersten Zeilen werden ausgegeben.
"""

import tensorflow as tf
import pandas as pd
from sklearn.model_selection import train_test_split

path = "/Users/student-sbs/PycharmProjects/KNN1/iris.csv"
data = pd.read_csv(path, delimiter=',')
print(data.head())

"""Daten vorbereiten."""

# Was soll vorhergesagt werden? Spaltenname in Variable speichern.
col_name = 'species'

# Zeichenkette in Zahlen umwandeln
data[col_name] = data[col_name].astype('category')
data[col_name] = data[col_name].cat.codes

# Hier findet die Aufteilung in zwei Tabellen statt (Input=data und Output=col).
col = data[col_name]
data = data.drop([col_name], axis = 1)

"""KNN aufbauen"""

# Aus den zwei Tabellen vier Tabellen erzeugen (20% Test/ 80% Training)
train_data, test_data, train_col, test_col = train_test_split(data,col, test_size=0.2, random_state=42)

# Aufbau KNN
model = tf.keras.Sequential()
model.add(tf.keras.Input(shape=(4,))) # 4 steht für die Anzahl der Spalten ohne Klasse-Spalte
model.add(tf.keras.layers.Dense(32, activation=tf.nn.sigmoid)) 
model.add(tf.keras.layers.Dense(64, activation=tf.nn.sigmoid)) # (Alternativ relu probieren)
model.add(tf.keras.layers.Dense(3, activation=tf.nn.softmax)) # 3 für 3 Output, weil 3 Klassen ausgegeben werden können

# Konfiguration des Lernprozesses
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
# sparse_categorical_crossentropy = Zielwerte sind Ganzzahlen

"""Trainieren"""
# 30 Durchläufe
model.fit(train_data, train_col, epochs=30)

"""Testen"""
test_loss, test_acc = model.evaluate(test_data, test_col)
print('Test accuracy:', test_acc)
